language: node_js
node_js:
  - 12.8.0
cache: npm

before_install:
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
